import {useEffect,useRef,useState} from 'react';
import api from '../../services/api';
import {useAuth} from '../../context/AuthContext';

const visitor=()=>{let id=localStorage.getItem('jls-support-visitor');if(!id){id=crypto.randomUUID();localStorage.setItem('jls-support-visitor',id)}return id};
export default function SupportWidget(){
 const {user}=useAuth(),[open,setOpen]=useState(false),[min,setMin]=useState(false),[items,setItems]=useState([]),[text,setText]=useState(''),[typing,setTyping]=useState(false),[conversationId,setConversationId]=useState(null),[canContact,setCanContact]=useState(false),end=useRef(null);
 const headers=user?{Authorization:`Bearer ${localStorage.getItem('jls-token')}`}:{},visitorId=visitor();
 useEffect(()=>{if(!open)return;api.get('/support/history',{params:{visitorId},headers}).then(r=>{setItems(r.data.items);setConversationId(r.data.conversationId)}).catch(()=>{});},[open,user]);
 useEffect(()=>{ end.current?.scrollIntoView({behavior:'smooth'}); },[items,typing]);
 const send=async e=>{e.preventDefault();const message=text.trim();if(!message||typing)return;setText('');setItems(old=>[...old,{role:'user',content:message,created_at:new Date().toISOString()}]);setTyping(true);try{const r=await api.post('/support/chat',{message,visitorId,conversationId},{headers});setConversationId(r.data.conversationId);setCanContact(r.data.canContact);setItems(old=>[...old,{role:'assistant',content:r.data.answer,created_at:new Date().toISOString()}])}catch(x){const unavailable=!x.response;setItems(old=>[...old,{role:'assistant',content:unavailable?'O backend do JL Registry está desligado. Execute npm run dev:all na pasta do projeto.':(x.response?.data?.error||'Não foi possível falar com o suporte agora.'),created_at:new Date().toISOString()}])}finally{setTyping(false)}};
 const contact=async()=>{const last=[...items].reverse().find(x=>x.role==='user')?.content||'Preciso de ajuda com o JL Registry.';try{const r=await api.post('/support/contact',{question:last},{headers});if(r.data.contactUrl)window.open(r.data.contactUrl,'_blank','noopener');setItems(old=>[...old,{role:'assistant',content:r.data.message,created_at:new Date().toISOString()}]);setCanContact(false)}catch{setItems(old=>[...old,{role:'assistant',content:'Não foi possível encaminhar agora.',created_at:new Date().toISOString()}])}};
 return <div className={`support-widget ${open?'is-open':''} ${min?'is-minimized':''}`}><button className="support-fab" aria-label="Abrir suporte" onClick={()=>{setOpen(true);setMin(false)}}>💬 <span>Suporte</span></button>{open&&<section className="support-chat" aria-label="Chat de suporte"><header><div><b>Suporte JL Registry</b><small>IA especializada no ecossistema JLScript</small></div><div><button title="Minimizar" onClick={()=>setMin(!min)}>—</button><button title="Fechar" onClick={()=>setOpen(false)}>×</button></div></header>{!min&&<><div className="support-messages">{items.length===0&&<div className="message assistant">Olá! Posso ajudar com login, bibliotecas, publicação, instalação e terminal.</div>}{items.map((m,i)=><div className={`message ${m.role}`} key={i}><span>{m.content}</span><small>{new Date(m.created_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small></div>)}{typing&&<div className="message assistant typing"><i/><i/><i/> IA digitando…</div>}{canContact&&<button className="contact-human" onClick={contact}>Falar com suporte humano</button>}<div ref={end}/></div><form className="support-form" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Digite sua dúvida…" aria-label="Mensagem para suporte"/><button className="button" disabled={typing}>Enviar</button></form></>}</section>}</div>;
}
